#!/bin/bash
# pydroid-automate.sh - Automate Pydroid 3 workflows with Obsidian
# 
# This script:
# 1. Monitors a Scripts/ directory for Python scripts
# 2. Executes them (using python3 or Pydroid 3)
# 3. Organizes outputs into an Outputs/ directory with timestamps
# 4. Generates Markdown notes in Notes/ referencing the outputs
#
# Usage: ./pydroid-automate.sh [OPTIONS]
# Options:
#   --scripts-dir DIR    Directory containing Python scripts (default: ./Scripts)
#   --output-dir DIR     Directory for outputs (default: ./Outputs)
#   --notes-dir DIR      Directory for generated notes (default: ./Notes)
#   --python CMD         Python command to use (default: python3)
#   --dry-run           Show what would be done without making changes
#   --verbose           Show detailed output
#   --cleanup           Remove processed scripts from Scripts/ after execution
#   --help              Show this help message

set -euo pipefail

# Defaults
SCRIPTS_DIR="./Scripts"
OUTPUT_DIR="./Outputs"
NOTES_DIR="./Notes"
PYTHON_CMD="python3"
DRY_RUN=false
VERBOSE=false
CLEANUP=false

# Parse arguments
while [[ $# -gt 0 ]]; do
  case "$1" in
    --scripts-dir)
      SCRIPTS_DIR="$2"
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR="$2"
      shift 2
      ;;
    --notes-dir)
      NOTES_DIR="$2"
      shift 2
      ;;
    --python)
      PYTHON_CMD="$2"
      shift 2
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    --verbose)
      VERBOSE=true
      shift
      ;;
    --cleanup)
      CLEANUP=true
      shift
      ;;
    --help|-h)
      echo "Usage: $0 [OPTIONS]"
      echo ""
      echo "Options:"
      echo "  --scripts-dir DIR    Directory containing Python scripts (default: ./Scripts)"
      echo "  --output-dir DIR     Directory for outputs (default: ./Outputs)"
      echo "  --notes-dir DIR      Directory for generated notes (default: ./Notes)"
      echo "  --python CMD         Python command to use (default: python3)"
      echo "  --dry-run           Show what would be done without making changes"
      echo "  --verbose           Show detailed output"
      echo "  --cleanup           Remove processed scripts from Scripts/ after execution"
      echo "  --help              Show this help message"
      exit 0
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

# Get repository root
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$REPO_ROOT"

# Log function
log() {
  if [ "$VERBOSE" = true ]; then
    echo "[VERBOSE] $1"
  fi
}

# Ensure directories exist
mkdir -p "$SCRIPTS_DIR" "$OUTPUT_DIR" "$NOTES_DIR"

# Temporary directory for processing
TMP_DIR=$(mktemp -d)
trap "rm -rf $TMP_DIR" EXIT

# Get timestamp for outputs
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Find all Python scripts in the Scripts directory
SCRIPTS=$(find "$SCRIPTS_DIR" -maxdepth 1 -type f -name "*.py" | sort)

if [ -z "$SCRIPTS" ]; then
  echo "No Python scripts found in $SCRIPTS_DIR"
  exit 0
fi

echo "Found $(echo "$SCRIPTS" | wc -l) Python script(s) to process"
echo ""

# Process each script
for script in $SCRIPTS; do
  SCRIPT_NAME=$(basename "$script" .py)
  SCRIPT_BASENAME=$(basename "$script")
  
  echo "========================================"
  echo "Processing: $SCRIPT_BASENAME"
  echo "========================================"
  
  # Create a working directory for this script
  SCRIPT_WORKDIR="$TMP_DIR/${SCRIPT_NAME}_$TIMESTAMP"
  mkdir -p "$SCRIPT_WORKDIR"
  
  # Copy script to working directory
  if [ "$DRY_RUN" = false ]; then
    cp "$script" "$SCRIPT_WORKDIR/$SCRIPT_BASENAME"
    log "Copied script to: $SCRIPT_WORKDIR/$SCRIPT_BASENAME"
  else
    echo "[DRY RUN] Would copy $script to working directory"
  fi
  
  # Determine output prefix
  OUTPUT_PREFIX="${SCRIPT_NAME}_${TIMESTAMP}"
  
  # Execute the script
  if [ "$DRY_RUN" = false ]; then
    echo "Executing: $PYTHON_CMD $SCRIPT_WORKDIR/$SCRIPT_BASENAME"
    
    # Run the script and capture output
    cd "$SCRIPT_WORKDIR"
    if $PYTHON_CMD "$SCRIPT_BASENAME" > "$SCRIPT_WORKDIR/output.log" 2> "$SCRIPT_WORKDIR/error.log"; then
      echo "Script executed successfully"
      log "Output: $(tail -5 "$SCRIPT_WORKDIR/output.log")"
    else
      echo "::warning::Script execution failed for $SCRIPT_BASENAME"
      echo "Error output:"
      cat "$SCRIPT_WORKDIR/error.log"
      # Continue processing other scripts
      continue
    fi
    cd "$REPO_ROOT"
  else
    echo "[DRY RUN] Would execute: $PYTHON_CMD $SCRIPT_WORKDIR/$SCRIPT_BASENAME"
  fi
  
  # Find all output files generated by the script
  # Exclude the script itself, log files, and hidden files
  OUTPUT_FILES=$(find "$SCRIPT_WORKDIR" -maxdepth 1 -type f ! -name "$SCRIPT_BASENAME" ! -name "output.log" ! -name "error.log" ! -name ".*" | sort)
  
  if [ -z "$OUTPUT_FILES" ]; then
    echo "No output files generated by $SCRIPT_BASENAME"
  else
    echo "Found $(echo "$OUTPUT_FILES" | wc -l) output file(s)"
    
    # Process each output file
    for output_file in $OUTPUT_FILES; do
      FILE_NAME=$(basename "$output_file")
      FILE_EXT="${FILE_NAME##*.}"
      FILE_BASE="${FILE_NAME%.*}"
      
      # Generate new filename with timestamp
      NEW_FILE_NAME="${OUTPUT_PREFIX}_${FILE_NAME}"
      
      # Determine destination path
      DEST_PATH="$OUTPUT_DIR/$NEW_FILE_NAME"
      
      if [ "$DRY_RUN" = false ]; then
        echo "  Moving: $FILE_NAME -> $DEST_PATH"
        mv "$output_file" "$DEST_PATH"
        
        # Generate relative path for Markdown reference
        REL_OUTPUT_PATH="$(realpath --relative-to="$NOTES_DIR" "$DEST_PATH")"
        
        # Create a Markdown note for this output
        NOTE_FILENAME="${OUTPUT_PREFIX}_${FILE_BASE}.md"
        NOTE_PATH="$NOTES_DIR/$NOTE_FILENAME"
        
        echo "  Generating note: $NOTE_PATH"
        
        # Create the Markdown note
        {
          echo "# ${SCRIPT_NAME} - ${FILE_NAME}"
          echo ""
          echo "Generated: $(date)"
          echo "Source Script: [$SCRIPT_BASENAME]($SCRIPTS_DIR/$SCRIPT_BASENAME)"
          echo ""
          
          # Handle different file types
          case "$FILE_EXT" in
            json)
              echo "## JSON Output"
              echo ""
              echo "\`\`\`json"
              cat "$DEST_PATH" | head -50
              echo "\`\`\`"
              echo ""
              echo "[Download]($REL_OUTPUT_PATH)"
              ;;
            png|jpg|jpeg|gif|svg)
              echo "![Output Image]($REL_OUTPUT_PATH)"
              echo ""
              echo "[View Image]($REL_OUTPUT_PATH)"
              ;;
            txt|log|md)
              echo "## Text Output"
              echo ""
              echo "\`\`\`"
              cat "$DEST_PATH" | head -100
              echo "\`\`\`"
              echo ""
              echo "[View Full]($REL_OUTPUT_PATH)"
              ;;
            csv)
              echo "## CSV Output"
              echo ""
              echo "\`\`\`csv"
              cat "$DEST_PATH" | head -20
              echo "\`\`\`"
              echo ""
              echo "[Download]($REL_OUTPUT_PATH)"
              ;;
            *)
              echo "## Output File"
              echo ""
              echo "File: [$FILE_NAME]($REL_OUTPUT_PATH)"
              echo "Type: $FILE_EXT"
              echo "Size: $(stat -c%s "$DEST_PATH" | numfmt --to=iec) bytes"
              ;;
          esac
          
          echo ""
          echo "---"
          echo "*Generated by pydroid-automate.sh*"
        } > "$NOTE_PATH"
        
        echo "  Created note: $NOTE_PATH"
      else
        echo "  [DRY RUN] Would move: $FILE_NAME -> $DEST_PATH"
        echo "  [DRY RUN] Would create note: $NOTES_DIR/${OUTPUT_PREFIX}_${FILE_BASE}.md"
      fi
    done
  fi
  
  # Cleanup: Remove processed script from Scripts/ directory
  if [ "$CLEANUP" = true ] && [ "$DRY_RUN" = false ]; then
    echo "Cleaning up: Removing $script"
    rm -f "$script"
  elif [ "$CLEANUP" = true ]; then
    echo "  [DRY RUN] Would remove: $script"
  fi
  
  echo ""
done

echo "========================================"
echo "Processing Complete"
echo "========================================"
echo "Scripts processed: $(echo "$SCRIPTS" | wc -l)"
echo "Outputs directory: $OUTPUT_DIR"
echo "Notes directory: $NOTES_DIR"

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "NOTE: This was a dry run. No changes were made."
  echo "Run without --dry-run to execute for real."
fi

echo "Done."
